name: Build and upload dist artifact

on:
  workflow_call:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    name: Build and upload dist artifact
    needs:
      - tests
    concurrency: build-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm clean-install

      - name: Build
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          retention-days: 1
          path: dist